apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-food-api-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fiap-food-api
      name: fiap-food-api
    spec:
      containers:
        - name: fiap-food-api-container
          image: fiapfastfood/fiap-api
          ports:
            - containerPort: 80
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
               secretKeyRef:
                 name: datasource_url
                 key: HOST
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
               secretKeyRef:
                 name: datasource_username
                 key: USER 
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
               secretKeyRef:
                 name: datasource_password
                 key: PASSWORD
            - name: DB_PORT
              valueFrom:
               secretKeyRef:
                 name: dbport
                 key: DBPORT
            - name: DB_NAME
              valueFrom:
               secretKeyRef:
                 name: dbname
                 key: DBNAME                  
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              valueFrom:
               secretKeyRef:
                 name: datasource_driver_class_name
                 key: DRIVER_CLASS_NAME
            - name: API_PAYMENT_URL
              valueFrom:
               secretKeyRef:
                 name: api_payment
                 key: HOST_API_PAYMENT                     
          livenessProbe:
            httpGet:
              path: /swagger-ui/index.html
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /swagger-ui/index.html
              port: 8080
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 3
          resources:
            requests:
              cpu: 30m
  selector:
    matchLabels:
      app: fiap-food-api
